# Generated by Django 4.1 on 2024-11-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Demo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_num", models.CharField(max_length=32)),
                ("park_name", models.CharField(max_length=32)),
                ("jinru_Date", models.CharField(max_length=32)),
                ("chuqu_Date", models.CharField(max_length=32)),
                ("time", models.CharField(max_length=32)),
            ],
        ),
    ]
