# Generated by Django 4.1 on 2024-11-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_demo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Demo",
        ),
        migrations.DeleteModel(
            name="VoteLog",
        ),
    ]
