# Generated by Django 5.1.3 on 2024-11-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_delete_demo_delete_votelog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vote',
            table='vote',
        ),
    ]
