-- CREATE DATABASE CISC7403_B5_DB;

\c postgres

create table vote
(
    id        bigint generated by default as identity
        constraint app01_vote_pkey
            primary key,
    choice    varchar(5)               not null,
    timestamp timestamp with time zone not null
);

alter table vote
    owner to jingguang;

-- INSERT INTO votes (name, vote_number, last_vote) VALUES ('Cats', 0, NOW());
-- INSERT INTO votes (name, vote_number, last_vote) VALUES ('Dogs', 0, NOW());
